# Generated by Django 5.0.6 on 2024-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('limit_number_car', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=100)),
                ('start_time_work', models.CharField(max_length=20)),
                ('end_time_work', models.CharField(max_length=20)),
                ('features', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
