# Generated by Django 5.0.6 on 2024-06-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinginfo',
            name='occupied_slots',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='parkinginfo',
            name='vacant_slots',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
