# Generated by Django 5.0.6 on 2024-06-23 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_reserve', '0002_parkinginfo_occupied_slots_parkinginfo_vacant_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(blank=True, max_length=6, null=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('plate_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=16)),
                ('checked_out', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_reserve.parkinginfo')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
